server.port=8080
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://192.168.0.200:15432/sample
spring.datasource.username=nobu
spring.datasource.password=n0buh1sa

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
